---
title: SztukaUniwersalna.PL
baseurl: ://sztukauniwersalna.pl/
timezone: Europe/Warsaw
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  drafts:
    title: Drafts
    output: false

