---
title: SztukaUniwersalna.PL
baseurl: ://sztukauniwersalna.pl/
timezone: Europe/Warsaw
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  drafts:
    title: Drafts
    output: false
topLinks:
  Moda: /sztuka-ubioru
  Makijaż: /sztuka-makijażu
  Kuchnia: /sztuka-gotowania
  Sztuka: /sztuka-dla-sztuki
  O mnie: /kim-jest-olela?
