---
title: SztukaUniwersalna.PL
baseurl: ://sztukauniwersalna.pl/
timezone: Europe/Warsaw
collections:
  pages:
    layout: PageLayout
  posts:
    layout: PostLayout
  Categories:
    layout: PostLayout
  uploads:
    title: Uploads
  drafts:
    layout: DraftLayout
    output: false
menu:
  - title: Sztuka Ubioru
    short: Moda
    url: /sztuka-ubioru/
    icon:
  - title: Sztuka Makijażu
    short: Makijaż
    url: /sztuka-makijażu/
    icon:
  - title: Sztuka Gotowania
    short: Kuchnia
    url: /sztuka-gotowania/
    icon:
  - title: Sztuka dla Sztuki
    short: Sztuka
    url: /sztuka-dla-sztuki/
    icon:
  - title: Kim jest Olela?
    short: O mnie
    url: /kim-jest-olela/
    icon:

