---
title: SztukaUniwersalna.PL
timezone: Europe/Warsaw
collections:
  categories:
    title: Categories
    output: false
    layout: PostLayout
  drafts:
    title: Drafts
    output: false
    layout: DraftLayout
  pages:
    title: Pages
    output: false
    layout: PageLayout
  posts:
    title: Posts
    output: true
    layout: PostLayout
  uploads:
    title: Uploads
    output: false
baseurl: "//sztukauniwersalna.pl/"
menu:
- title: Sztuka Ubioru
  short: Moda
  url: "/sztuka-ubioru"
  icon: content_cut
- title: Sztuka Makijażu
  short: Makijaż
  url: "/sztuka-makijazu"
  icon: remove_red_eye
- title: Sztuka Gotowania
  short: Kuchnia
  url: "/sztuka-gotowania"
  icon: restaurant
- title: Sztuka dla Sztuki
  short: Sztuka
  url: "/sztuka-dla-sztuki"
  icon: palette
- title: Kim jest Olela?
  short: O mnie
  url: "/kim-jest-olela"
  icon: mood
