---
title: SztukaUniwersalna.pl
timezone: Europe/Warsaw
collections:
  categories:
    title: Categories
    layout: ParrotLayout
  pages:
    title: Pages
    layout: ParrotLayout
  posts:
    title: Posts
    layout: ParrotLayout
  uploads:
    title: Uploads
    output: false
baseUrl: http://sztukauniwersalna.pl
image: http://sztukauniwersalna.pl/logo-gradient.png
locale: pl_PL
menu:
- title: Sztuka Ubioru
  short: Moda
  url: "/sztuka-ubioru"
  icon: content_cut
- title: Sztuka Makijażu
  short: Makijaż
  url: "/sztuka-makijazu"
  icon: remove_red_eye
- title: Sztuka dla Sztuki
  short: Sztuka
  url: "/sztuka-dla-sztuki"
  icon: palette
- title: O Blogu
  short: O Blogu
  url: "/sztuka-uniwersalna"
  icon: mood
- title: Kontakt
  short: Kontakt
  url: "/kontakt"
  icon: email
