---
title: SztukaUniwersalna.PL
baseurl: ://sztukauniwersalna.pl/
timezone: Europe/Warsaw
collections:
  pages:
    title: Pages
  posts:
    title: Posts
  uploads:
    title: Uploads
  drafts:
    title: Drafts
    output: false
categories:
  kuchnia:
    title: Sztuka Gotowania
  moda:
    title: Sztuka Ubioru
  makijaż:
    title: Sztuka Makijażu
  sztuka:
    title: Sztuka dla Sztuki
menu:
  - title: Sztuka Ubioru
    short: Moda
    url: /sztuka-ubioru
    icon:
  - title: Sztuka Makijażu
    short: Makijaż
    url: /sztuka-makijażu
    icon:
  - title: Sztuka Gotowania
    short: Kuchnia
    url: /sztuka-gotowania
    icon:
  - title: Sztuka dla Sztuki
    short: Sztuka
    url: /sztuka-dla-sztuki
    icon:
  - title: Kim jest Olela?
    short: O mnie
    url: /kim-jest-olela
    icon:

